Book-Library features
uche-inyama/Library-project pull request #1
Opened 2019-11-14 12:01 UTC by uche-inyama

2019-11-19 10:46 UTC, shloch commented
### PR under review by SHEY LOUIS CHIA

2019-11-19 11:07 UTC, shloch commented on index.html
> +            /><br />
Hello great job for your project, please look for a way to control the submission of an empty form. "Empty" books can be added. You either add the option `required` to these inputs, or you control that with javascript

2019-11-19 11:09 UTC, shloch requested changes
### Please fix the minor issue above and file for a Re-review 
### Happy coding 😊😊

2019-11-19 20:20 UTC, JamesOkunlade requested changes
# Changes required 🙁 

The book is not being added to the library as it is throwing a validations error.
```
Please check, a required field(s) are empty
```
Pls check this and request another review.

James Okunlade

2019-11-20 12:30 UTC, SunnyAsar approved these changes
# Hello @uche-inyama  and @IBTechRaj 👋
## Looking Good ✨  Please proceed

# You May Pass 👍

2019-11-23 11:45 UTC, merged